# Generated by Django 4.0.2 on 2022-02-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_email', models.CharField(max_length=50)),
                ('buyer_password', models.CharField(max_length=50)),
                ('buyer_phone', models.CharField(max_length=50)),
                ('buyer_address', models.TextField()),
                ('buyer_dob', models.DateField()),
            ],
            bases=('orm.role',),
        ),
    ]
